# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt6 UI code generator 6.5.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import sys
import pandas as pd
import pyzard
import selenium
import time
from selenium.webdriver.common.alert import Alert
import time
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
import subprocess
import doubleagent
from selenium.webdriver.support.select import Select
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.chrome.service import Service
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.keys import Keys

from selenium.webdriver.common.by import By
import random
import string



chrome_options = Options()
chrome_options.add_experimental_option("debuggerAddress", "127.0.0.1:9222")
service = Service("chromedriver.exe")
driver = webdriver.Chrome(service = service, options=chrome_options)
driver.switch_to.window(driver.window_handles[0])

while True:
    df_from_excel = pd.read_csv('댓글로그인.csv')

    df_from_excel2 = pd.read_csv('댓글컨텐츠.csv')
    time.sleep(2)
    elem = driver.get("https://healthyflow.co.kr/exec/front/Member/logout")
    time.sleep(2)
    elem = driver.get("https://healthyflow.co.kr/member/login.html?noMember=1&returnUrl=%2Forder%2Forderform.html%3Fbasket_type%3DA0000%26delvtype%3DA&delvtype=A")

    triger = df_from_excel.values.tolist()
    if len(triger) == 0:
        break
    login_lst = df_from_excel.values.tolist()[0]
    comment_lst = df_from_excel2.values.tolist()[0]
    print(login_lst)
    print(comment_lst)

    while True:
        try:                            
            elem = driver.find_element("xpath",'/html/body/div[3]/div/form/div/div/fieldset/label[1]/input').send_keys(login_lst[0])

            break
        except:

            time.sleep(2)
    while True:
        try:                   
            elem = driver.find_element("xpath",'/html/body/div[3]/div/form/div/div/fieldset/label[2]/input').send_keys(login_lst[1])

            break
        except:

            time.sleep(2)

    while True:
        try:                   
            elem = driver.find_element("xpath",'/html/body/div[3]/div/form/div/div/fieldset/a').click()

            break
        except:

            time.sleep(2)
    da = Alert(driver)
    dacounter1 = 0
    while True:
        if dacounter1 == 2:
            break
        try:
            da.accept()
            break
        except:
            time.sleep(1)
            dacounter1 = dacounter1+1

    driver.get("https://healthyflow.co.kr/board/review/write.html?board_no=4&product_no=13&cate_no=42&display_group=1")
    while True:
        try:                   
            elem = driver.find_element("xpath",'//html/body/div[3]/div/div/form/div/div[2]/table/tbody[1]/tr[1]/td/input').send_keys(comment_lst[0])

            break
        except:

            time.sleep(2)  

    document = driver.find_elements(By.TAG_NAME,'iframe')

    driver.switch_to.frame(document[0])

    while True:
        try:                   
            elem = driver.find_element("xpath",'/html/body/p').send_keys(comment_lst[1])

            break
        except:

            time.sleep(2)  

    driver.switch_to.default_content()
    time.sleep(1) 
    while True:
        try:                   
            elem = driver.find_element("xpath",'/html/body/div[3]/div/div/form/div/div[3]/span[2]/a[1]').click()

            break
        except:

            time.sleep(2)  



    df_from_excel.drop(0,  inplace=True)
    df_from_excel2.drop(0,  inplace=True)
    df_from_excel.to_csv('댓글로그인.csv', index=False)
    df_from_excel2.to_csv('댓글컨텐츠.csv', index=False)
